version: '3'
services:
    koe:
        build:
            context: ./
        ports:
            - "5000:5000"
        tty: true
        volumes:
            - ./app:/usr/local/app
            - ./tests:/usr/local/tests
            - ./storage:/usr/local/storage
        container_name: koe_app
